-- Deprecated prototype schema.
-- The backend now uses ../vyuha_database_build_steps.sql as its canonical PostgreSQL schema.
-- SQLAlchemy models in database.py provide the local SQLite development projection.
